AQI:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt_AQI
      threads: 1
      type: postgres
      user: postgres
  target: dev
